services:
  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
volumes:
  pgdata: